### PR TITLE
Fixed displaying wrong days in timetable

### PR DESCRIPTION
**Pull request by pzfl**
There was a bug, that made the timetable display only the current day. This patch fixes this.

### CODE REVIEW

**Comment by thomai** [comment]
Nice move! @FHellmann ? :+1:

**Comment by FHellmann** [comment]
I've already fixed this issue with my [latest commit](https://github.com/Fachschaft07/fs-app/commit/b43175b9808e62f60da4f01b0aac0ff9dc0d1508). But I will have a look at your code @FPar and decide which solution I will use. Thank you! ;)

**Comment by FPar** [comment]
You made [another change](https://github.com/Fachschaft07/fs-app/blob/e1422d24931fffd38686620b820ef275ab1b84c6/app/src/main/java/edu/hm/cs/fs/app/ui/timetable/TimetableAdapter.java#L166), which broke it again, that in the portrait mode only the current day is shown multiple times.

**Comment by FHellmann** [comment]
I haven't tested it yet, so maybe yes. I will test your code and integrate it then.

**Comment by FPar** [comment]
Great :smile:

**Pull request merged**
